### ISSUE TITLE
turblinks not traps link with method DELETE

### ISSUE THREAD

**Issue by edwardbako** [turbolinks/turbolinks#10]
I'm using rails helper and it looks like this

`link_to message, @message,  method: :delete`

But it performed without turbolinks, even if I specify 

`link_to message, @message,  method: :delete, data: {turbolinks: true}`

Is turbolinks skips this kind of links? How can I force this link to perform by turbolinks?

**Comment by packagethief** [comment]
Hi Edward --

While it looks like a plain old link, adding `method: delete` causes Rails to generate an inline form element and submit it with its method set to `DELETE`. Because what results is a form and not a link, it's not handled by Turbolinks.

You can make your link submit via XHR, though, and take advantage of Turbolinks' Rails integration for a speedy response without a full load. To do this, add the `remote: true` option to your link:

```ruby
link_to "delete", @message, method: :delete, remote: true
```

This will produce a normal (annotated) link that when clicked will perform the request in the background using XHR. If you respond on the server by redirecting with `redirect_to`, Turbolinks' Rails integration will detect this and automatically convert the redirect into a call to `Turbolinks.visit()`. The browser will evaluate this response and perform a Turbolinks visit without reloading the page. The link will behave just as you'd expect with Turbolinks.

Give that a shot and let me know how it goes!

**Comment by edwardbako** [comment]
Hi @packagethief,
 
Thanks for your response. 

It is new for me to hear that Rails generates an inline form. Actually I'am checking browser and `link_to` helper produces this html `<a rel="nofollow" data-method="delete" href="/messages/91">X</a>`. How can I understand that it is an inline form?

**Comment by edwardbako** [comment]
Hi @packagethief,

Thanks for your response.

It is new for me to hear that Rails generates an inline form. I'am checking browser and `link_to` helper produces this html `<a rel="nofollow" data-method="delete" href="/messages/91">X</a>`. How can I understand that it is an inline form?

I've tried your solution and now it produces XHR call and processed by Turbolinks. Super! Additionally, I want use some hooks on `'turbolinks:click'` event. For example, I use this trick to retain scroll position.

```
$(document).on 'turbolinks:click', (event)->
  window.prevPageYOffset = window.pageYOffset
  window.prevPageXOffset = window.pageXOffset

$(document).on "turbolinks:load", ->
  window.scrollTo window.prevPageXOffset, window.prevPageYOffset
```

So, first event is not trigered by clicking on that link. I could writing another event listener on that links. But why should I do that?

**Comment by packagethief** [comment]
> It is new for me to hear that Rails generates an inline form. I'am checking browser and link_to helper produces this html <a rel="nofollow" data-method="delete" href="/messages/91">X</a>

The inline form is created with JavaScript. Rails provides the `data-method` annotation, which Rails' UJS adapter looks for when a link is clicked. [It creates a form, adds it to the DOM, and submits it](https://github.com/rails/jquery-ujs/blob/master/src/rails.js#L210-L229).

> So, first event is not trigered by clicking on that link. I could writing another event listener on that links.

Yes, you'll need to add your own event listener for clicks on such links. Turbolinks installs itself as the last click handler on links. If an earlier handler stops propagation or prevents the default action ([as Rails' UJS adapter does](https://github.com/rails/jquery-ujs/blob/master/src/rails.js#L425-L426)), the click will never reach Turbolinks.

**Comment by edwardbako** [comment]
@packagethief,

As Turbolinks is last click handler, XHR initiated by UJS not Turbolinks and progres bar is not initiated. If any reason response takes some time to arive, we have no indication of progress.
How to tackle this issue?
Is there some other logic trigered by `Turbolinks.visit()`?

**Comment by packagethief** [comment]
Hi Edward --

You're right that a non-Turbolinks XHR request won't display the progress bar.

I'd suggest listening for clicks on your link and displaying a custom activity indicator. Probably something small and close to the element at hand, like an animated spinner.
