### ISSUE TITLE
Problem with turbolinks:load including initial page load

### ISSUE THREAD

**Issue by pbougie** [turbolinks/turbolinks#115]
I'm having trouble adding page tracking with [Gauges](http://get.gaug.es/) when using Turbolinks. Gauges automatically tracks a page when the script is embedded in a page. Therefore, placing it in the body tracks each page twice when a previously cached page is visited. Moving the script into the head section tracks the page on initial page load but not for Turbolinks visits.

If we add a little code, we can also track Turbolinks visits but there is a problem with the events. Using `turbolinks:load` will track the initial page load twice. Using any event before `turbolinks:load` will track the page twice in certain instances or track the wrong page title.

Maybe a new event that does not include the initial page load is required? Or a way to exclude the initial page load from `turbolinks:load`. Is there a verification in JS that can tell us if the page was loaded using Turbolinks? If so, I could use `turbolinks:load` and simply exclude the tracking on initial page load.

Rails: `4.2.6`
Turbolinks: `5.0.0.beta5`

**Comment by packagethief** [comment]
Hey @pbougie. One way to detect the initial page load is to inspect the `event` data on `turbolinks:load`. On the initial load, `event.data.timing.visitStart` will be undefined.


```js
document.addEventListener("turbolinks:load", function(event) {
  if (!event.data.timing.visitStart) {
    // Initial page load
  } else {
    // Turbolinks page load
  }
})
```

Of course, this is totally not obvious and feels like a hack. It would be much nicer if we had an `event.data.initialPageLoad` boolean so we can be explicit.

Is that something you're interested in exploring in a PR?

**Comment by pbougie** [comment]
Hi @packagethief. Looks like I got it working based on your suggestion. Here's what I did:

```js
document.addEventListener('turbolinks:load', function(event) {
  if (event.data.timing.visitStart) {
    _gauges.push(['track']);
  }
})
```
I only need the method to be executed when the page is loaded using Turbolinks. Not sure I understand when the visit timing metrics are started. Are `event.data.timing.visitStart` and `turbolinks:visit` related in any way in the lifecycle?

Not sure `event.data.initialPageLoad` would be less of a hack. Wouldn't an event that excludes the initial page load make more sense? I'm currently migrating an app from Pjax and I was a little confused at first that `turbolinks:load` included the `ready` event.

**Comment by packagethief** [comment]
In most cases you don't need to distinguish between the initial page load and subsequent Turbolinks loads. That's why there's a single `turbolinks:load` event.

For the rare cases where you do need to distinguish, it's usually because loading a script performs some action that can't be prevented (as is the case with Gauges). Since this is infrequent, I don't think it's worth the conceptual overhead of an additional event.

I still like the idea of adding an `initialPageLoad` boolean to the event data on `turbolinks:load`, though, and it doesn't feel like a hack to me at all. It lets us keep a single, unambiguous event to notify applications about page loading, and provides an extra bit of information about the nature of the page load for the rare case where it matters.

I'm going to close this issue now since the workaround above is effective (an alternative is simply to track whether `DOMContentLoaded` has fired and ignore the next `turbolinks:load` if so). If you're interested in adding an `initialPageLoad` option, I'd be more than happy to review a pull request.

**Comment by pbougie** [comment]
Ok. I’ll look into creating a PR but my CoffeeScript is non-existent.

**Comment by neohunter** [comment]
I need to distinguish it because i'm doing some animations, i dont want it to execute the animation on the first page.

`if (event.data.timing.visitStart) {`

works fine but is not redeable, why not create a new attribute to identify if is a load by turbolinks, something like

`event.data.turbolinks_request `

or 

`event.data.initial_page_load `

**Comment by nateberkopec** [comment]
@neohunter maintainers have already said that they would accept such a PR if it was submitted

**Comment by benningm** [comment]
Please have a look at #286
