### ISSUE TITLE
Body not being replaced after form submission

### ISSUE THREAD

**Issue by bryanvero** [turbolinks/turbolinks#119]
I have added `:remote => true` to my devise sign_up form, and I can see that now the form is being submitted via XHR, and that the response comes back with the proper HTML that should be shown (showing validation failures), but Turbolinks is not replacing the HTML content.

My `application.js` is simple:
```
//= require jquery
//= require jquery_ujs
//= require turbolinks
```

Why isn't the body being replaced?

**Comment by packagethief** [comment]
Hi @bryanvero. Turbolinks doesn't handle XHR form submission. If you want to update the page in response to an XHR, you can return a JavaScript string and evaluate it. Since you're using Rails with jQuery, the JavaScript response will be evaluated automatically.

This technique is known generally as ["Server-generated JavaScript Responses"](https://signalvnoise.com/posts/3697-server-generated-javascript-responses) or SJR for short. You can read the linked article for an explanation and some examples.

**Comment by codyrobbins** [comment]
See #85 for a more complete discussion.
