### ISSUE TITLE
Turbolinks should allow user control of progress bar delay

### ISSUE THREAD

**Issue by AnthonySuper** [turbolinks/turbolinks#120]
Turbolinks currently displays the progress bar for requests that take 500ms. I believe that this value should be user-configurable.

While fast page loads are great, 500ms is more than enough to notice a delay. This can lead to a frustrating user experience, as they believe that their click has not worked for half a second before the progress bar shows up. The majority of my page loads do take under 500ms (thankfully), but those that don't can be frustrating for users.

I know that other people obviously has different opinions, so I believe that this option should be (in some way) configurable, either through the approach used by Turbolinks classic, or through a `<meta>` tag. I'd be happy to submit a patch if the maintainers agree with me.

I know there was some past discussion of ideas similar to this in #44, but it focused more on the virtues of a JS-specific API rather than the ability to set this delay in general.

**Comment by sstephenson** [comment]
I’m open to making the 500ms delay configurable. If you’d like to explore that with a pull request, please go ahead!

I don’t think a page-specific setting is appropriate. I can’t see why you’d want the delay to be variable depending on the page, so I’d suggest making it configurable with JavaScript instead of a `<meta>` tag.

Note that if the app is running inside the iOS or Android adapters, `Turbolinks.controller.adapter` will not be an instance of `Turbolinks.BrowserAdapter`, and the app won’t have a progress bar at all. Whatever API we decide on for setting this value will need to work regardless of the current adapter.

**Comment by AnthonySuper** [comment]
Would it be acceptable if the API for setting the progress bar delay simply did nothing on iOS and Android?

**Comment by sstephenson** [comment]
Yeah, it should do nothing. Just need to make sure it doesn’t require the user to write a conditional in order to avoid an exception.
