### ISSUE TITLE
Fix links in right sidebar of Rubygems?

### ISSUE THREAD

**Issue by claudiob** [turbolinks/turbolinks#129]
The links:

- Homepage
- Source Code
- Documentation
- Bug Tracker

at https://rubygems.org/gems/turbolinks point to different repositories. 

Some reference the old rails/turbolinks, some reference turbolinks/turbolinks and other ones refer turbolinks/turbolinks-rails.

I'm not sure how to change them and what is the correct value, but I think it's something that needs some cleaning.

**Comment by packagethief** [comment]
Thanks for the heads-up! I've cleaned up the links.

The "Homepage" link remains confusing, though. It points to [turbolinks/turbolinks-rails](https://github.com/turbolinks/turbolinks-rails) as configured by the [gemspec](https://github.com/turbolinks/turbolinks-rails/blob/6fc2ac5/turbolinks.gemspec#L9).

Since there's no documentation at turbolinks-rails, I think we should set the homepage to this repository.

/cc @sstephenson

**Comment by sstephenson** [comment]
Done! 

https://github.com/turbolinks/turbolinks-rails/compare/v5.0.0...v5.0.1
https://rubygems.org/gems/turbolinks
