### ISSUE TITLE
Turbolinks breaks Bootstrap v4 Alpha Dropdown behavior

### ISSUE THREAD

**Issue by ewollesen** [turbolinks/turbolinks#170]
Steps to reproduce:
1. Generate a page with a bootstrap dropdown menu.
2. Follow a link in said dropdown.
3. Try to open the dropdown menu again, it refuses to open.

I looked into the code a little, it seems that when the dropdown meny link is followed, at first everything looks fine, but as soon as the dropdown is clicked the second time (before the code that opens the dropdown runs), it acquires the "open" class.\* Then the code the opens the dropdown runs, sees the open class, and returns, leaving the dropdown closed.

*I wasn't able to determine how the open class gets added here.

Disabling turbolinks fixes the problem.

If this is a twitter bootstrap issue, please let me know, and I'll gladly file an issue there, but since disabling turbolinks fixed it, my best guess was that it's a turbolinks issue?

**Comment by jacek213** [comment]
Very similar thing happened to me when using materializecss navbar dropdown ... I wanted to give the new turbolinks a chance but I'm not going to debug third party code which gets broken because of them again ...

**Comment by sintro** [comment]
Long story about fixing third-party JS libraries after enabling turbolinks. For turbo links 3 everything could be fixed by using jquery.turbolinks gem (https://github.com/kossnocorp/jquery.turbolinks), or by manual initialization of libraries inside $(document).on('page:load') event. Sad, but new turbolinks is much more difficult and you can not fix everything by just replacing 'page:load' with 'turbolinks:load'.

**Comment by serradura** [comment]
@ewollesen @jacek213 @sintro I think that the #213 has a possible answer for this issue.

**Comment by sintro** [comment]
@serradura , this is nice explanation, and may be that is correct solving of the problem, but, as I can remember, when I was trying to solve this problem, I considered this case (some clearing in html state in different sorts of _before hooks), and had no success. May be I had mistakes in my code, may be the problem was in another place.

**Comment by zacmp** [comment]
Adding `data-turbolinks-eval=false` to the other `<script>` tags loaded seems to be a workaround; it worked for me on Bootstrap v4.
https://github.com/turbolinks/turbolinks-classic/issues/539#issuecomment-105162751

**Comment by 1ulce** [comment]
I have same problem. I tried with
rails 5.2.0
gem 'bootstrap-sass', '~> 3.3.7'
gem 'sass-rails' 

in application.js.coffee
#= require jquery
#= require bootstrap-sprockets
#= require rails-ujs
#= require activestorage
#= require turbolinks
#= require_tree .

in <head> with slim file
`= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', 'data-turbolinks-eval': false`
seems bootstrap got multiple times.

**Comment by domchristie** [comment]
I'm unable to reproduce this using the latest version of bootstrap, or with version 3.3.7. If you are still experiencing this problem, you may be able to get some help by posting a question on Stack Overflow (ideally with a live demo), tagged with Turbolinks. Thanks.
