### ISSUE TITLE
How to handle js/css assets per layout?

### ISSUE THREAD

**Issue by ghaydarov** [turbolinks/turbolinks#193]
I have more than one layout, and different assets per layout in rails app. When I visit a page with layout A, it saves the head, and if I load a page with layout B, it appends both layout assets files to the head. So, on one page I have two different assets where I should have only one. Any ideas how to solve this problem? Thanks!

**Comment by nateberkopec** [comment]
See #187 (though your sheets are external rather than inline)

**Comment by Fudoshiki** [comment]
@ghaydarov
You can add
```ruby
gem 'turbolinks', git: 'https://github.com/Sharevari-Inc/turbolinks-source-gem'
```
in `Gemfile` as temp solution https://github.com/turbolinks/turbolinks/pull/189

**Comment by domchristie** [comment]
This is by design. Turbolinks tends to work smoothly when the number of assets is minimised—ideally packaged up in to a single JS file and a single CSS file. When it loads a new page as "sees" new assets in the `<head>`, it merges them in, and evaluates them without fully reloading the page. If Turbolinks notices that assets no longer exists (or have changed), it will perform a full page load, so one possible solution would be to have separate application manifest files for each layout. This would trigger a full page load, so unfortunately you'd be missing out on the performance benefits when switching layouts.
