### ISSUE TITLE
Angular Material not working with Turbolinks

### ISSUE THREAD

**Issue by kulvir97** [turbolinks/turbolinks#194]
Hello,

I'm building a website with Bootstrap and for styling the forms and buttons, i'm using Angular Material in it. 
![1](https://cloud.githubusercontent.com/assets/21354127/19315555/c1826414-90bb-11e6-8859-37cd44f8bf72.jpg)

But, when i applied Turbolinks, the page loads faster and works everything fine except Angular Material. Turbolinks doesn't loads the css and js files for Angular Material.
![2](https://cloud.githubusercontent.com/assets/21354127/19315563/caf2b652-90bb-11e6-9f00-459e057681c9.jpg)

How can i fix this?

Thanks

**Comment by nateberkopec** [comment]
Since I don't think this is a bug in Turbolinks (Turbolinks isn't really designed to work with "single-page" Javascript frameworks like Angular), you may be better off asking StackOverflow for this question.

**Comment by domchristie** [comment]
When a third-party library works on the first page load but not subsequent ones, it is usually because it is not being initialised when Turbolinks loads a page (i.e. on `turbolinks:load`). Often libaries automatically initialise themselves on `DOMContentLoaded` or `$(document).ready`, but will often need manual initialisation on `turbolinks:load`. It's also worth noting that third-party libraries often need tearing down (often termed `destroy`) on `turbolinks:before-cache` to prevent it from being initialised twice when tapping "Back".

Please checkout the README and the [FAQ](https://github.com/turbolinks/turbolinks/wiki/Turbolinks-5-FAQ#will-my-third-party-libraries-work-with-turbolinks-5) to learn more about how Turbolinks works. Hope that helps.
