### ISSUE TITLE
Easy way to keep overflow:scroll element scrolling position during changes?

### ISSUE THREAD

**Issue by sixtyfive** [turbolinks/turbolinks#2]
In the following scenario, is there now a way to preserve the `<aside>` element's scrollbar position?

HTML:
```
%body
  %aside{'data-turbolinks-permanent': true}
    %ul
      - @lotsofthingies.each do |thingy|
        -# First, this:
        %li= link_to(thingy)
  %article{'data-turbolinks-temporary': true}
    -# Remote-submitted form be here, which is cool. But then, also this:
    = link_to 'Delete thingy!', @thingy, method: :delete, remote: true
```

CSS:
```
body, aside
  height: 100%
body
  overflow-y: hidden
aside
  overflow-y: scroll
```

I'm aware of https://github.com/turbolinks/turbolinks-classic/pull/528, so my question is mostly whether the `data-turbolinks-scroll="false"` idea mentioned there has been implemented in some way meanwhile?

On the other hand, using `TurboLinks.visit(thingy_url, {scroll: false})` still resets the `<aside>`'s scrollbar position, so perhaps what I'm trying to achieve doesn't work that way, either...

**Comment by sstephenson** [comment]
Thanks for opening this issue.

First, we won’t be adding a `data-turbolinks-scroll` annotation or a `scroll: false` option to `Turbolinks.visit`. Scrolling is carefully coordinated by the view to match the browser’s normal navigation behavior, and depends on what the visit action is, whether there’s a cached snapshot, whether the location has an anchor, and whether the cached snapshot has an element matching that anchor. 

We may consider some mechanism in the future to preserve the scroll position of overflow elements which are marked as permanent, or are inside a permanent container. However, this is expensive for a number of reasons: there is no easy way to query for such overflow elements without an explicit annotation; querying `scrollTop` causes reflow; and finally, just because an element is permanent does not mean it will have the same dimensions from one page to the next, and so preserving its scroll position may not even be possible.

Going forward, the approach I’d like to take for cases like this is to expose the necessary hooks such that applications or third-party libraries can customize rendering behavior as necessary. To that end, I’ve opened PR #5, which adds a `turbolinks:before-render` event. Using this event, you ought to be able to preserve overflow scroll offsets on permanent elements like so:

```js
(function() {
  var scrollTops = new WeakMap

  function findElements() {
    return document.querySelector("[data-turbolinks-permanent]")
  }

  addEventListener("turbolinks:before-render", function() {
    findElements().forEach(function(element) {
      scrollTops.set(element, element.scrollTop)
    })
  })

  addEventListener("turbolinks:render", function() {
    findElements().forEach(function(element) {
      if (scrollTops.has(element)) {
        element.scrollTop = scrollTops.get(element)
      }
    })
  })
})()
```

**Comment by sixtyfive** [comment]
All completely reasonable and wow, thank you so much for the explanation and the `.patch`, @sstephenson!

**Comment by dsmithco** [comment]
Here's how I handled this...

```
// in application.js

var turbolinks_go = function(url, no_scroll){
  if(no_scroll){
    addEventListener("turbolinks:before-render", function() {
      scroll = $(document).scrollTop();
    })
    addEventListener("turbolinks:render", function() {
      $(document).scrollTop(scroll);
    })
  }
  Turbolinks.visit(url);
}

// then calling it anywhere on the site

turbolinks_go(location.toString(), 'no_scroll');
```

**Comment by FrankFang** [comment]
But a browser reloading does keep the body's scrolling position.
How could I make it happen via Turbolink? 
`Turbolink.visit(location.href, scroll: false)` doesn't work now.

**Comment by domo1664** [comment]
You have to pass the second parameter as an object like this and it works.
```Turbolinks.visit(location.href, {scroll: false});
