### ISSUE TITLE
Turbolinks:load event in new head scripts is not been triggered when click a new link

### ISSUE THREAD

**Issue by sakeyu** [turbolinks/turbolinks#212]
In the ReadMe, it said:
> When you navigate to a new page, Turbolinks looks for any <script> elements in the new page’s <head> that aren’t present on the current page. Then it appends them to the current <head> where they’re loaded and **evaluated by the browser**. **You can use this to load additional JavaScript files on-demand.**

I visit a page that has new script in the head from a new link, and i have some code in the _new_script.js_:
```javascript
document.addEventListener("turbolinks:load", function () {
    //........
});
```

the turbolinks:load event is not been triggered when nav to the new page at first time, but triggered when nav from other pages next time, Is this a issue or my understanding is wrong?

**Comment by fordfischer** [comment]
I ran into this initially, but it is actually doing what you tell it to. It adds an Event Listener (but that happens after the `turbolinks:load` event). So it only executes after you navigate to another page. 

If you are putting on that page, and you want it to execute on page load, don't put it inside of an event listener.

**Comment by obromios** [comment]
[fordfic](https://github.com/fordfischer) I would like to understand this behaviour better, as it appears to relate to a[ question](http://stackoverflow.com/questions/41421496/turbolinks-load-event-not-working-on-with-page-refresh) I have asked on SO.  In that case, I am putting the script in a file located under app/assets/javascript.  The code looks something like this:

```
 ready = ->
    if $('body').attr('data-loaded') == 'T'
      return
    # code goes here
    $('body').attr('data-loaded','T')
  $(document).on('turbolinks:load', ready)
```

The javascript in the script is not triggering when I first go to a page or refresh a page, but does work when I click to or go back to it.  From what you are saying the reason for this is that when the javascript is first loaded, it attaches the listener, but by then the turbolinks:load event has occured, so the code is not triggered. This would seem to apply whether the code is put in script element in the head, or pre-compiled into application.js from the assets/javascript directory. Is this correct?

If that is correct, there are a few things I do not understand about the behaviour.  In production mode the javascript code does not trigger on the initial visit, but in development mode the code does trigger on the initial visit, what is that?

Given I thought this was a problem rather than expected behaviour, I tried to debug this problem by generating a dumy new rails app, and gradually adding layouts, javascript, gems, initializers, layouts, etc in an effort to duplicate this behaviour, but I have been unable to do this.  The javascript runs first time in production and development mode in this dummy app. Why would this be?

The way I have solved the problem in the dummy app is to add a listener for the page load and a guard clause to stop the code triggering twice i.e.
```
 ready = ->
    if $('body').attr('data-loaded') == 'T'
      return
    # code goes here
    $('body').attr('data-loaded','T')
  $(document).ready(ready)
  $(document).on('turbolinks:load', ready)
```
This is not pretty, is there a better way to do this? Is there a switch I am missing or something like that?

**Comment by obromios** [comment]
After making the above comment, I think I worked out what the code acts differently in production. In production in the real app, I load the application.js with ```async: true```. When I added this to the dummy app, the same issue appeared, i.e. the code does not trigger on the initial page load unless I add an extra ``` $(document).ready(ready)```. 

So I can ask my question more concisely. How do I get my  javascript to run when loading a new page if I am using ```async: true``` and turbolinks 5?

**Comment by danielpclark** [comment]
I run into this issue every now and then.  To trigger the first load I use the following CoffeeScript code at the end of my CoffeeScript file.

```coffee
if !Turbolinks?
  location.reload

Turbolinks.dispatch("turbolinks:load")
```
So if `Turbolinks` is `undefined` it reloads the page and then the load hook is triggered.  Yes there are times where `Turbolinks` is `undefined`.  I have two similar Rails apps and I went through the same steps in making them and one has `Turbolinks` defined where the other one won't the first time.  They both need the `dispatch` method called to load the first time.

**Comment by LucasArruda** [comment]
Awesome tip @danielpclark

**Comment by domchristie** [comment]
@sakeyu Turbolinks activates new script elements in the `head` before triggering `turbolinks:load`, so this shouldn't be happening in normal situations :/

If your script element is loaded asynchronously (i.e. it includes an `async` attribute), then you might observe this issue as @obromios has noticed. My advice would be to load scripts without the `async` attribute.

**Comment by frederikhors** [comment]
Can you help me with something similar here, please? https://github.com/turbolinks/turbolinks/issues/489
