### ISSUE TITLE
Turbolinks 5 breaks dropdowns in Bootstrap 3.3.5

### ISSUE THREAD

**Issue by haslinger** [turbolinks/turbolinks#213]
I'm using Turbolinks as an npm module in a Phoenix app. 
When the site is opened, everything is fine, but after the first Turbolinks-enabled link is clicked, Bootstrap's dropdowns are no longer working (the dropdown does not drop down).

Interestingly enough, `Turbolinks.start();` is not even necessary for this, importing Turbolinks alone causes this behaviour.
Adding ` data-no-turbolink="true"` does not help in this case.
Adding `'data-turbolinks-eval'="false"` like described in [this stackoverflow post](http://stackoverflow.com/questions/26132384/bootstrap-3-dropdown-doesnt-work-with-rails-4-turbolinks) would help, but breaks javascript at several other places.

**Comment by serradura** [comment]
Hello @haslinger,

I'll try to help you with this issue. :)

First of all, what is your Turbolinks version? Because, the data-no-turbolink="true" is related with the turbolinks-classic, and this repo is about the Turbolinks 5. So I will answer your question, using the TL5.

Let's go to the problem...

I recorded a gif to show which kind of changes the Bootstrap collapse plugin will make in your html elements.
![gif](http://g.recordit.co/SfxLKdQSv7.gif)

And before continue, I recommend you to stop and read this documentation section: https://github.com/turbolinks/turbolinks#making-transformations-idempotent to understand whats happen with the state of your html elements, before a page visit occur.

How you saw in the gif, the navbar click/tap will change the html, and when you visit another page the TL5 will cache the page structure. So, when you back to this page/resource, the state of the navbar will be "shown" (the element thats store this data is hidden .navbar-collapse). The answer to make everything works is: You'll need to collapse the menu before the visit occur. e.g:

```javascript
  document.addEventListener('turbolinks:before-visit', function() {
    var $navbar = $('.navbar-collapse');
    
    if ( $navbar.hasClass('in') ) {
      $navbar.collapse('hide');
    }
  });
```

And to help you and others, I created a sample project showing everything works together.
https://github.com/serradura/bootstrap-and-turbolinks5

PS: There is two branches in the repo.
1. `3.3.7` - Bootstrap 3.3.7 + jQuery 3.1.1
2. `3.3.5` - Bootstrap 3.3.5 + jQuery 1.12.4

**Conclusion:**
The problem isn't TL5, but the bootstrap collapse. Because it wont work without the right initial state.

**Comment by haslinger** [comment]
Hi, @serradura, thanks for your efforts, but I was talking about dropdowns as in http://getbootstrap.com/components/#dropdowns.

The issue is more, that after the first turbolink enabled link has been used, bootstrap's javascript never get's initialized again for the new elements on the page.  I am not about coming back to a page, just following one turbolinks enabled link.

But, the problem seems to be a different one ;-) 
I had my <script> tag as the last one in the <body>, so probably it got reevaluated.
Putting it in the head fixed the issue alltogether!

**Comment by rssluca** [comment]
Hi,

I am having a similar issue. My dropdown menu is no longer working.

I am using data-no-turbolink="true" in the a tag but no luck. When I debug (attribute modification) the link it looks like the link is opened twice as I can see the dropdown menu appearing and disappearing as the "elem.setAttribute( name, value + "" ); " is fired twice.

How can I prevent this?

**Comment by Davidslv** [comment]
I've just encounter the same situation and I've solved it with the following code:

```javascript
function toggleDropdown(element) {
  var dropdown = new Dropdown(element);
  dropdown.toggle();
}

document.addEventListener('turbolinks:load', function() {
  var dropdown_buttons = document.querySelectorAll('[data-toggle="dropdown"]');

  dropdown_buttons.forEach(function(element) {
    element.addEventListener('click', function(event) {
      event.preventDefault();

      toggleDropdown(this);
    });
  });
});
```

I hope you find it useful, you can adapt it to your needs.

**Comment by richardkeep** [comment]
@Davidslv  I am getting an error `Uncaught ReferenceError: Dropdown is not defined`. Where is it defined?

**Comment by glenn6452** [comment]
Add this on your headers.
`<meta name="turbolinks-visit-control" content="reload">`

**Comment by macgadger** [comment]
Hi @Davidslv , I am getting an error Uncaught ReferenceError: Dropdown is not defined. Where is it defined? Can you please elaborate?

**Comment by macgadger** [comment]
> @Davidslv I am getting an error `Uncaught ReferenceError: Dropdown is not defined`. Where is it defined?

Hi @richardkeep , I resolved it but adding dropdown-toggle class to drop-down on href or buton under dropdown class and add this to script:
```
document.addEventListener('turbolinks:load', function() {
    $('.dropdown-toggle').dropdown();
});
```
:)
