### ISSUE TITLE
Menu not working with turbolinks

### ISSUE THREAD

**Issue by wonderer007** [turbolinks/turbolinks#220]
I am using [metisMenu](https://github.com/onokumus/metisMenu) for menu, it works fine if without turbolinks but when I add turbolinks in application.js it works only once when i reload the page then after 1 click can't open menu. Help Needed 

Thanks

**Comment by alexspark** [comment]
After looking at metisMenu homepage, if you have code similar to the following: 
```javascript
$(function () {
    $('#menu2').metisMenu({ toggle: false });
});
```
then, it would explain the problem you've described: 
```
it works only once when i reload the page
```
When you fully reload the page, the jQuery `ready` event will be emitted and your code will probably work, and no longer on subsequent page navigations.

```
... after 1 click...
```
Could you expand on what you meant by this? If you clicked on an `<a>` tag or somehow triggered a page navigation, then the jQuery `ready` event does not fire for those subsequent page visits. You may have to change your javascript to listen for the `turbolinks:load` event instead of using `$()` that is so prevalent in many jQuery plugins.

Their README covers what it takes to enhance your javascript to work well with turbo links. Specifically [this section](https://github.com/turbolinks/turbolinks#running-javascript-when-a-page-loads) may help you.

**Comment by wonderer007** [comment]
Yes [Running JavaScript When a Page Loads](https://github.com/turbolinks/turbolinks#running-javascript-when-a-page-loads) works for me
```
document.addEventListener("turbolinks:load", function() {
  $('#side-menu').metisMenu({toggle: false });
})

```
@alexspark Thanks for you comment

**Comment by domchristie** [comment]
Closing as solved
