### ISSUE TITLE
Visiting Turbolinks enabled links in Chrome shows the page with no CSS for a split second before showing it normally

### ISSUE THREAD

**Issue by Arif59** [turbolinks/turbolinks#242]
**How to replicate:**

1. Visit http://photoid.herokuapp.com/users/sign_in on Chrome
2. Go back and forth between 'Login' page and the 'Register' page from the links on the navbar
3. You'll see that the page is displayed with no CSS for a second or two before changing to normal

**Screenshots:**

No CSS:

![screenshot_2017-03-01_12-57-36](https://cloud.githubusercontent.com/assets/20640302/23449055/ccc9de2a-fe7e-11e6-8fc4-a22d0517baed.png)

With CSS:

![screenshot_2017-03-01_12-57-48](https://cloud.githubusercontent.com/assets/20640302/23449076/df17e518-fe7e-11e6-9c5e-b29fdc3dcc0d.png)

This doesn't happen in Firefox. I've tested it only on Chrome and Firefox so far so I cannot speak for other browsers. Please look into this. Thanks!

**Comment by packagethief** [comment]
Hey @Arif59! I don't think this is a Turbolinks problem. The issue appears to be with your site's HTML. The stylesheet links, in Chrome, are being rendered inside the `<body>` element. That's what's causing the flash of unstyled content – your stylesheets are being reloaded on each render.

This is probably because the markup has an errant closing `</html>`:

```html
<!DOCTYPE html>
<html></html>
<head>
```

<img width="493" alt="screen shot 2017-03-01 at 10 06 15 am" src="https://cloud.githubusercontent.com/assets/10987/23465719/1ebca59a-fe67-11e6-8463-10adc1dc9237.png">
