### ISSUE TITLE
Merge jplayer and turbolinks

### ISSUE THREAD

**Issue by leknoppix** [turbolinks/turbolinks#283]
Hi all!

I'm trying to merge turbolinks library end Jplayer library.
But, I have a problem with Chrome. On this browser.
When I change the page, the player goes out in chrome, while under firefox and edge, no worries, the player continues to turn.

I charge in my template a player.js to initialize the player:
```
jQuery(function($) {
    $(document).ready(function() {
        //Player audio
        var stream = {
            title: "My title",
            mp3: "http://link"
        };
        ready = false;
        $("#jquery_jplayer_1").jPlayer({
            ready: function (event) {
                ready = true;
                $(this).jPlayer("setMedia", stream).jPlayer("play");
            },
            pause: function () {
                $(this).jPlayer("clearMedia");
            },
            error: function (event) {
                if (ready && event.jPlayer.error.type === $.jPlayer.error.URL_NOT_SET) {
                    // Setup the media stream again and play it.
                    $(this).jPlayer("setMedia", stream).jPlayer("play");
                }
            },
            swfPath: "js/",
            supplied: "mp3",
            preload: "auto",
            volume: 0.4,
            wmode: "window",
            useStateClassSkin: true,
            autoBlur: false,
            keyEnabled: true
        });
    });
});
```
And this file have the attribute data-turbolinks-eval="false".

I give you an example: https://goo.gl/R0Ditz

Do you look my error?
Thanks

I have put the attribute data-turbolinks-permanent on my player html

**Comment by domchristie** [comment]
Hi @leknoppix 

When working with third-party libraries, like jQuery plugins, you may want to consider using the `turbolinks:load` event rather than `$(document).ready`. I also noticed that you have nested jQuery ready functions: `jQuery(function($) {…})` is shorthand for `$(document).ready(function() {…})`, so you can remove these and try `$(document).on('turbolinks:load', function() {…})` instead.

To play audio continuously across pages, you may be able to get some ideas from this comment: https://github.com/turbolinks/turbolinks/issues/157#issuecomment-423275861. If you continue to have issues, please ask a question on StackOverflow tagged with 'turbolinks'. Thanks!
