### ISSUE TITLE
Save data and eventHandlers before cache

### ISSUE THREAD

**Issue by mintuhouse** [turbolinks/turbolinks#30]
A few JS libraries set the guard condition based on `.data()` & if I call their `init()` function on `turbolinks:load` it leads to duplicate elements/eventHandlers as associated data is discarded from Turbolinks.Cache
e.g., 
````
function init(){
  if(!elem.data('initialized')){
    // Create a few hidden/ support elements
    // Initialize event handlers
  }
}
````
Since this behaviour is different from normal browser behaviour i.e., when I press browser back, both data and eventHandlers are also restored, would it be possible to correct it.

1. Is it an acceptable approach to use [`jQuery(element).clone(true).get(0)`](https://api.jquery.com/clone/) instead of `element.cloneNode(true)` when jQuery is defined, so that atleast the users who already use jQuery can take advantage of it?
2. What is the recommended way to handle above cases - with or without editing the library code?

[Original issue](https://github.com/FezVrasta/bootstrap-material-design/pull/882#issuecomment-189580331) I faced - the library checks whether to initialize an element or not based on data("mdproc") which is not set when I visit the same page via browse back/forward

**Comment by tomfakes** [comment]
This helped me change the code in my app to work with Turbolinks, but isn't a way to make Turbolinks work with arbitrary javascript libraries that hookup in unusual ways.

For Event Handlers, the best way to make these persist between turbolink loads is to add them to the document.  Here's an example:

Instead of:
`  $(".foo .bar").on("some-event", function() {});
`

I do this:
`  $(document).on("some-event", ".foo .bar", function() {});
`

The key is to NOT re-add them on every Load event, as this duplicates the event hookup each time, wasting memory and slowing down the page for all.  It turns out this is a best practice anyway, as, instead of each '.foo .bar' having data added, only a single event is added to a single element (the document).

For my own script loading, I used a global javascript variable to indicate the one-time init is done - this isn't as clean as adding a data attribute to an element, but this flag does persist between turbolinks pages!

Here's an example extracted from my code - this one loads an external script that is only used on a few of my pages:

```
var isFooLoaded = false;
$(document).on('turbolinks:load', function() {
  
  if (isFooLoaded) 
    initFoo();
  else {
    $.getScript("foo.js", function() {
      isFooLoaded = true;
      initFoo();
    });
  }

});

```

This code could easily be added to an existing javascript class definition to remove it from the global scope too, but this works for my code right now.  With 1 other tweak, I managed to get the Payola Payments gem working in my Rails 4/Turbolinks 5 app.

**Comment by packagethief** [comment]
> Is it an acceptable approach to use jQuery(element).clone(true).get(0) instead of element.cloneNode(true) when jQuery is defined, so that atleast the users who already use jQuery can take advantage of it?

I don't think so. We'd like to avoid any dependency on jQuery or other libraries, even if it's optional.

> What is the recommended way to handle above cases - with or without editing the library code?

Instead of using element data to track initialization, use an HTML5 `data-*` attribute. Attributes are preserved when Turbolinks clones nodes.

To modify your example:

```js
// Mark the element as initialized using a data-* attribute
element.setAttribute("data-mdproc", "")

// Check for the data-* attribute before re-initializing
function init() {
  if (!element.hasAttribute("data-mdproc")) {
    // ...
  }
}
```

Of course, unless you own the library, you won't be able to control this. In those cases, @tomfakes's advice is good: use a local variable to track whether initialization has been performed.

@tomfakes, you can avoid needing to set a global variable by wrapping your initialization code in an [immediately invoked function expression](https://en.wikipedia.org/wiki/Immediately-invoked_function_expression). This way your "loaded" variable remains private, visible only inside the function:

```js
(function() {
  var loaded = false

  $(document).on("turbolinks:load", function() {
    if (!loaded) {
      // load it up
      loaded = true
    }
  })
})()
```

**Comment by tomfakes** [comment]
I do need to wrap that puppy up.  

I'm still working through issues with external code and getting an understanding of how this works.  Is there likely to be a Wiki page for getting specific external code working with Turbolinks 5?  I have a few pieces I could contribute

**Comment by mintuhouse** [comment]
Using IIFE along with a private variable visible only to my initialization code would avoid double initialization but the event listeners also [seem](https://github.com/turbolinks/turbolinks/blob/93f56a107549ed00c5609fbc09190b6d77008d60/README.md#understanding-caching) to be discarded. The library I am using (say [timepicker](https://github.com/Eonasdan/bootstrap-datetimepicker)) need not provide handlers to just add listeners to existing DOM elements.

One option is to replicate the behaviour of jQuery.clone inside Turbolinks to ensure back button behaviour remains same as browser's default
I tried to go through jQuery's [code](https://github.com/jquery/jquery/blob/b0b280cd61d1fa12b67bd723ac2c2fa91b92db01/src/manipulation.js#L233) but it seemed daunting. Is it worth the effort?

**Comment by packagethief** [comment]
> One option is to replicate the behaviour of jQuery.clone inside Turbolinks to ensure back button behaviour remains same as browser's default. I tried to go through jQuery's code but it seemed daunting. Is it worth the effort?

I'd say no. The benefit of using `cloneNode()` and discarding event listeners is that Turbolinks is less likely to leak memory. This was an intentional decision.

In most cases you should be able to tear down 3rd party widgets on `turbolinks:before-cache`, and set them up again on `turbolinks:load`.

The [datetimepicker](https://github.com/Eonasdan/bootstrap-datetimepicker) widget you linked is a good example. It provides a destroy function that we can use to uninstall it before Turbolinks caches the page. The trick is keeping a reference to the picker object so we can call `destroy()` on it:

```js
(function() {
  var picker = null

  document.addEventListener("turbolinks:load", function() {
    $("#datetimepicker").datetimepicker()
    picker = $("#datetimepicker").data("DateTimePicker")
  })

  document.addEventListener("turbolinks:before-cache", function() {
    if (picker) {
      picker.destroy()
      picker = null
    }
  })
})()
```

**Comment by mintuhouse** [comment]
Thankyou @packagethief for taking time to explain in detail. We can document (or link above comment) an example of this (probably in [Responding to Page Updates](https://github.com/turbolinks/turbolinks#responding-to-page-updates) section) so it may help others.
