### ISSUE TITLE
cdnjs doesn't have min version.

### ISSUE THREAD

**Issue by alfa-jpn** [turbolinks/turbolinks#307]
Hello,

I use turbolinks with cdnjs. ( https://cdnjs.com/libraries/turbolinks )
But,  cdnjs hasn't had a min version since version 5.0.1. 

How do i solve it?

Best regards,

**Comment by javan** [comment]
I see all of the versions on cdnjs. <img width="591" alt="screen shot 2017-07-25 at 7 45 50 am" src="https://user-images.githubusercontent.com/5355/28570652-14bbd098-710d-11e7-84b2-1bdcda846825.png">
I suggest contacting them if you see something else.

**Comment by alfa-jpn** [comment]
@javan Thanks for reply.

This is a question about the minify version.

`https://cdnjs.cloudflare.com/ajax/libs/turbolinks/5.0.0/turbolinks.min.js` is existing.

but,

`https://cdnjs.cloudflare.com/ajax/libs/turbolinks/5.0.3/turbolinks.min.js` is not existing.

Is this project not a manager for cdnjs released libraries?

**Comment by javan** [comment]
Hmm, I'm not sure where `turbolinks.min.js` and `turbolinks.min.js.map` came from in https://cdnjs.com/libraries/turbolinks/5.0.0. It's possible they were created by cdnjs because [they weren't in the 5.0.0 release](https://github.com/turbolinks/turbolinks/tree/f25a427d31b22f3ad383ab101294c6863e26bc52/dist) and I also don't see them on other CDNs like https://unpkg.com/turbolinks@5.0.0/dist/.

**Comment by alfa-jpn** [comment]
@javan 
Thanks for reply.

I misunderstood the mechanism of cdnjs...
This issue is triggered by auto-update.
https://github.com/cdnjs/cdnjs/commit/79a30a84aab96d3070451c029b46dcdf44d1e57f

I want the builder create turbolinks.js (no compressed) and turbolinks.min.js (compressed) in dist directory.

I think that it can create with node and gulp.
Can I send a PR?
