### ISSUE TITLE
data-turbolinks-permanent does not maintain value after application visit occurs to a page without the element ID

### ISSUE THREAD

**Issue by vaharoni** [turbolinks/turbolinks#32]
Perhaps this is not the intention of `data-turbolinks-permanent`, but here is a use case to consider:
* Page 1 contains a dropdown marked with `data-turbolinks-permanent`. When the page loads it contains the value "A".
* User changes the dropdown value to "B".
* User performs an application visit to Page 2 that does not contain that dropdown.
* User clicks on the back button. Page 1 is restored from the cache. The value of the dropdown is loaded from the cache as "A", effectively reverting the changes made by the user.

I get that idempotent JS code needs to be reapplied on restoration visits. It would be really nice if there was also an easy way to maintain value of elements that are not intended to be JS-controlled. Applying such value maintenance behavior for elements marked as `permanent` seems to be a pretty intuitive way to go.

Here is a repo that contains a basic example to play with:
https://github.com/vaharoni/turbolinks5-permanent-issue

**Comment by packagethief** [comment]
Hey @vaharoni. Thanks for providing an example.

The behavior you observed happens because the value of form elements isn't stored in the DOM and may not survive `cloneNode()`. Consequently, it can't be cached by Turbolinks.

The selected state of a `<select>` element is an example of something that doesn't persist after cloning:

```js
document.querySelector("select").selectedIndex # => 2
document.querySelector("select").cloneNode().selectedIndex # => -1
```

On the other hand, some elements' values are preserved. For example, text inputs:

```js
document.querySelector("input[type=text]").value # => "hello"
document.querySelector("input[type=text]").cloneNode().value # => "hello"
```

Alas, this behavior is inconsistent across browsers. In Chrome, the contents of a `<textarea>` survives being cloned, but not in Safari or Firefox:
  
```js
document.querySelector("textarea").value # => "hello"
document.querySelector("textarea").cloneNode().value # => ""
```

I don't think Turbolinks should take on the responsibility of maintaining these values, especially given the inconsistencies across browsers.

I'm not even sure how we'd be able to map elements to values without requiring each to have a unique identifier. If you had multiple `<select>` elements in a permanent container, and bearing in mind that nodes are cloned using `cloneNode()`, how would you know which elements had which values?
