### ISSUE TITLE
"turbolinks:load" event not work when including a special js file using content_for 

### ISSUE THREAD

**Issue by GreatVincy** [turbolinks/turbolinks#326]
I am using _Turbolinks5_ on _Rails 5_.In order to reduce the of assets,I am trying to include the javascript file in the page on demand. 
> in  layout file (app/views/layouts/application.html.erb)
```
<head>
......
<%= yield :javascripts %>
</head>
```
> in view file (app/views/tests/index.html (i.e. this page use application.html.erb as it's layout ))
````
<% content_for :javascripts do %>
 <%= javascript_include_file "js_for_special_page" %>
<% end %>
````
> in js file (app/assets/javascripts/special/js_for_special_page.js)
```
console.log('file executed!')
$(document).on("turbolinks:load",function(){
  console.log('event triggered!')
})
```
It not worked as my expected...
There is the output of browser console:
+  enter the url in the browser or visit the page from other pages:
```
file executed!
```
+ type Trubolinks.visit(url) in browser console:
```
file executed!
```
+ press the refresh button on the browser:
```
file executed!
event triggered!
```
+ leaving the page:
```
file executed!
event triggered!
```
+ comeback to the page from other pages
```
file executed!
event triggered!
``` 
Why can't I trigger the event when the first time I visit the page?
Is there any idea to deal with this problem?
Are there other methods including special js file for special page?
Thanks!

**Comment by leahprin** [comment]
I am having this exact same issue. I've re-read the scripts section of the readme so many times and I'm going crazy.

**Comment by domchristie** [comment]
Are you able to provide a live demo of this behaviour?

**Comment by dritir** [comment]
Not sure if related, I am using jquery-rails gem, when requiring jquery3 turbolinks will not trigger on url+enter, f5, ctrl+f5.. but will trigger if a link is clicked.

when jquery2 is required it works 100%.

**Comment by domchristie** [comment]
I have tried to reproduce this here: https://fierce-everglades-74108.herokuapp.com/posts, but have been unable to do so.

I have tried to create a Rails app with a set up as close as possible to what you have described. There’s a `yield :javascript` in the head, and I load `posts.js` when `posts#index` loads using `content_for :javascript`. I have included jQuery 3 via a CDN.

`posts.coffee` looks like:

```coffeescript
console.log('**posts.js executed!**')
$(document).on('turbolinks:load', () ->
  console.log('**turbolinks:load in posts.js**')
)
```

Loading `/posts` via the address bar, or performing a page refresh, results in both the file being executed, as well as the `turbolinks:load` handler being called.

Loading `/posts/new` via address bar, then tapping “Back” to visit the index page, results in only the file being executed. In this case, I think this is what’s happening:

1. Click on “Back” link
2. Request is made to `/posts/index`
3. Turbolinks creates the new `<script>` in the `<head>` (which starts it downloading)
4. Turbolinks replaces the body
5. Turbolinks fires `turbolinks:load`
6. Script finishes downloaded and executes

So Turbolinks fires `turbolinks:load` before the script has finished loading meaning the handler won’t get called :/

You may be able to fix this by _rendering_ the javascript in the head, rather than making a request for it. However, I’d generally recommend against dynamically adding scripts for particular pages, as this often causes confusion (if event listeners are not removed for example). If possible include all your JavaScript in a single, and use the presence or absence of elements on the page to determine when to run a particular chunk of code.

**Comment by GreatVincy** [comment]
Thanks [_domchristie_](https://github.com/domchristie) very much !
Any `<script src="xxx">` label added to document **dynamically**  will be loaded **asynchronously**,
and the 'turbolinks:load' event  is always triggered before the script finish loading.
That's why 'turbolinks:load' event in the new script not work .

**Comment by domchristie** [comment]
Yes, that’s right. If your HTML is something like:

```html
<head>
  <script src="application.js"></script>
  <script src="js_for_special_page.js"></script>
</head>
```

then on the first **full** page load, `js_for_special_page.js` will block the HTML parsing, and should work as expected (`turbolinks:load` will be fired after the HTML has parsed, and so your event handler should be called).

As you have mentioned, if you visit this page via a Turbolinks link, then it will be loaded asynchronously. Turbolinks does not wait for asynchronous scripts to load (it might not perform very well if it did).

I’d recommend that you include as much JS in your application file as possible. If that’s not possible, you could render the JavaScript file contents (rather than load it asynchronously).

```html
<!-- app/views/tests/index.html -->
<script><%= render('specials/js_for_special_page.js').html_safe %></script>
```

To make this work, you’ll need to move your JavaScript into your `app/views/specials` directory, and be sure that it is safe to render (i.e. any user input is escaped if applicable)

**Comment by estani** [comment]
I had the same issue described here, I solved it by initializing everything in a init function which will get called immediately:

    var initPage = function() {
      var element = document.getElementsByTagName('vue-app');
      if (element.length > 0) { 
        // ... your whole vue.js code in here
      }
    }
    initPage(); //this triggers the loading at the time the script is full
    document.addEventListener('turbolinks:load', initPage); //this set the trigger for page changes

It looks is doing exactly what is supposed it should. If I'm missing something please do tell me.
