### ISSUE TITLE
Call jQuery#remove on detached elements

### ISSUE THREAD

**Issue by printercu** [turbolinks/turbolinks#332]
Hi!

There is commit (https://github.com/turbolinks/turbolinks-classic/pull/502) in turbollinks-classic which introduced running `.remove()` on node when it's detached from dom. I can not find similar in version 5. Has it been removed?

I don't think turbolinks should provide this workaround, but can you please tell what is the best place to setup hook for this?

Rationale for this issue, is that jquery is used in many libraries (ex. Bootstrap 3 & 4), and jquery stores custom data (ex, Bootstrap plugin instance) and event listeners in global `$.cache` along with element this data is attached to. The only way to clear this cache from old entries is to call `.remove()` on elements which are to be removed. Other way this data and elements are kept even when `Turbolinks.clearCache()` is called.

**Comment by sstephenson** [comment]
The best place to clean up after jQuery is in the `turbolinks:before-cache` event, which is triggered just before Turbolinks swaps the document body.

You’ll probably want to call [`jQuery.cleanData()`]9https://github.com/jquery/jquery/blob/731c501155ef139f53029c0e58409b80f0af3a0c/src/manipulation.js#L285-L317) instead of `.remove()`. Otherwise you’ll remove the elements themselves from the DOM before Turbolinks can cache a copy.

**Comment by printercu** [comment]
Ah, it removes event listeners too, so this should work. Should this be places to readme/cookbook (if there any)?

Thank you!

**Comment by printercu** [comment]
It also looks like `.cleanData()` doesn't use jquery's internal `getAll` method while `.remove()` does. This means app should run `$('body').find('*').andSelf().cleanData()`.
