### ISSUE TITLE
Turbolinks misses some elements on visit

### ISSUE THREAD

**Issue by narendraj9** [turbolinks/turbolinks#344]
I am using turbolinks on a static site: https://vicarie.in/ 

If you click on Posts, you can see that the heading of the page is missing. Similarly clicking a post link, we visit the post page with no heading. On refreshing the page, the heading appears. So, turbolinks is not adding `<div> <h1> Post/Page Heading </h1> </div>` to the page at all.

**Comment by packagethief** [comment]
Hi @narendraj9.

I don't think this is a Turbolinks issue.

It looks like this is due to the markup on the index page. It includes an inline `<style>` that hides elements with a class of `.title`. Because it's in the `<head>` it persists when navigating to "Posts" with Turbolinks and makes the `<h1 class="title">` invisible.

As you can see in this screenshot, the element is present:

<img width="873" alt="screen shot 2018-01-04 at 2 41 36 pm" src="https://user-images.githubusercontent.com/10987/34581267-d867e916-f15d-11e7-8539-93d1f6f82cd7.png">

Side-note, you should include `turbolinks.js` in the `<head>` of your document (see https://github.com/stimulusjs/stimulus/issues/33#issuecomment-355146405).

**Comment by narendraj9** [comment]
@packagethief Oh, I now understand what really happened. It's on the index page and it was merged onto pages that I visited from `/index.html`. Thanks a lot! :) You are amazing!

**Comment by narendraj9** [comment]
@packagethief 
What would be the ideal way of dealing with such cases?

**Comment by packagethief** [comment]
Ideally your `<head>`, including scripts and styles would remain the same across pages. Turbolinks replaces only the `<body>`.

**Comment by narendraj9** [comment]
@packagethief Thanks, closing the issue :)
