### ISSUE TITLE
turbolinks-cache-control no cache, form post and back button

### ISSUE THREAD

**Issue by juanbrein** [turbolinks/turbolinks#356]
Basically I have a form that when submitted, it delete and create objects into a database. 

I've set the turbolinks-cache-control to disable cache on the form page. This is mainly to handle a user pressing on the back button. If that happens, the form use objects ids that have already been deleted, so when you click back ... the old ids are populated rather than the new ones. That's the main purpose of disabling cache in that form.

Now I can confirm if I enable turbolinks-cache-control no-cache widely, it works as expected on any other link. When I click back... the pages are reloaded from the server. But with any other form, I can't achieve the same behavior. I looked into different places but couldn't find an answer.

I could achieve it setting request headers, but I'd like to handle this with turbolinks if possible

Should I be using a different mechanism?

Thanks in advance

Juan

**Comment by obnijnil** [comment]
I manually call `Turbolinks.clearCache()` on the form's `ajax:success` event.

**Comment by domchristie** [comment]
Hi @juanbrein, as @obnijnil mentions, if you have a form that is likely to affect the content of other pages, you can call `Turbolinks.clearCache()` when the form submission completes (See [Following Redirects](https://github.com/turbolinks/turbolinks#following-redirects) for more on this. If there is a particular page which changes a lot, then use the `no-cache` directive on that page (rather than on the form page). Hope that helps.
