### ISSUE TITLE
Turbolinks-Location header and redirects - source code question

### ISSUE THREAD

**Issue by SqueezedLight** [turbolinks/turbolinks#362]
Hi guys,
i'm trying to make use of the `Turbolinks-Location` header after a successful redirect. Redirect works, see this image (an already signed in user gets redirected to the dashboard):

<img width="957" alt="bildschirmfoto 2018-02-08 um 09 08 17" src="https://user-images.githubusercontent.com/3613734/35961957-d1df21c8-0caf-11e8-8755-698f9ebfbc03.png">

As this picture shows, the `Turbolinks-Location` header is present in the 302 server-response. But it seems `Turbolinks` only evaluates the `Turbolinks-Location` for http status codes between 200&300. See the source code here: https://github.com/turbolinks/turbolinks/blob/c73e134731ad12b2ee987080f4c905aaacdebba1/src/turbolinks/http_request.coffee#L30-L37

Here is my question: Why? Most redirects have status code 301 or 302. Therefore the description in the readme file makes not much sense to me:

> To work around this problem, send the Turbolinks-Location header in response to a visit that was redirected, and Turbolinks will replace the browser’s topmost history entry with the value you provide.
 

I'm sure you guys implemented it due to some reason. Please enlighten me and tell me how to work around this problem ;)

Thanks in advance!

**Comment by packagethief** [comment]
> Here is my question: Why? Most redirects have status code 301 or 302

Hey! Good question. It's because Turbolinks issues XHR requests, and XHR always follows redirects. That's why Turbolinks needs a header to tell it whether a visit was redirected before reaching its final destination. Otherwise it has no way of knowing that the response came from a different URL.

The wording in the README is kind of confusing:

> send the Turbolinks-Location header in response to a visit that was redirected

This means, "send the header in your 200 response when you know that it was arrived at by redirection." Clear as mud, right? 😂 

So, when issuing a redirect, keep track of the location (say, in a cookie). Then, when you receive a request for that location, include the header in your response.

That's how the Rails plugin works. When you use `redirect_to` it [stores the location in the session](https://github.com/turbolinks/turbolinks-rails/blob/2cf8ef328e9aa1ba0224f68620a20e2445d13bbb/lib/turbolinks/redirection.rb#L17). Then, [on every request](https://github.com/turbolinks/turbolinks-rails/blob/2cf8ef328e9aa1ba0224f68620a20e2445d13bbb/lib/turbolinks/redirection.rb#L6), it [checks for the presence of a location in the session](https://github.com/turbolinks/turbolinks-rails/blob/2cf8ef328e9aa1ba0224f68620a20e2445d13bbb/lib/turbolinks/redirection.rb#L43) and if found, includes it in the `Turbolinks-Location` header of the response.

The [turbolinks-location](https://github.com/sandinmyjoints/turbolinks-location) package takes a different approach. It always sets the header. That should work fine too, and I'm having trouble remembering why we didn't choose to do that for the Rails plugin!

**Comment by SqueezedLight** [comment]
@packagethief thanks for the very good explanation and the links. This really is great information! 

Do i get it right - the reason that 301&302 status codes are excluded from evaluating the `Turbolinks-Location` header is, because otherwise (especially in case of multiple redirects) the browser history would get cluttered with unwanted entries. So you narrow it down to success status codes to be sure only the final destination gets the header? This might also be an explanation for the rails approach? Or am i wrong?

**Comment by packagethief** [comment]
> Do i get it right - the reason that 301&302 status codes are excluded from evaluating the Turbolinks-Location header is ... the browser history would get cluttered with unwanted entries?

No, it's that because XHR follows redirects, we'll never receive a 3xx in the code you linked to 😄  The browser will continue following redirects until it receives a non-redirect response. So, anything other than 2xx is treated by Turbolinks as an error.
