### ISSUE TITLE
Option to access the newBody in before-cache event callback

### ISSUE THREAD

**Issue by mintuhouse** [turbolinks/turbolinks#37]
This question is slightly related to another [issue](https://github.com/turbolinks/turbolinks/issues/30), where to avoid double initialization - I could add just destroy the initialized widget manually before it is saved to cache. And reinitialize it from scratch next time the page is loaded (from back button or @cache )

But in the following simplified use-case, it would cause flickering/sudden DOM changes:
Lets say I click on a link(coming from external library) in a dropdown inside a permanent element, I want to destroy the current dropdown object only if it is not present in the next page as this is inside permanent element. This would avoid the flickering behaviour or sudden closing of dropdown. (Though I still have to solve some event listeners related issues)

I am currently using existing `request-end` event and modify the current DOM based on `xhr.response` - but I would have to construct DOM manually (which would be discarded immediately after the callback) - `newBody` attribute similar to `before-render` would be more handy. 

Another alternative is to triggering `before-render` before `before-cache`, but it may have some side-effects for people already using the library

**Comment by packagethief** [comment]
Hey @mintuhouse,

I understand the problem you're describing, but I don't think you should make caching decisions based on an upcoming render. Since you can't control the order of navigation, you won't be able to guarantee that you've cached the page in a state that's compatible with future visits.

In the scenario you described, consider what would happen with a permanent widget that exists on pages A and B, but not on C. When navigating from A -> B, A's expanded widget would be saved to the cache and persist on page B. When you navigate from B -> C, the widget would be removed. If you then use history to navigate from C -> A, you'd see the cached widget in its expanded state.
