### ISSUE TITLE
JS breaks when going back to previous page rails

### ISSUE THREAD

**Issue by JulienCorb** [turbolinks/turbolinks#399]
I use turbolinks 5.
I have a carousel, a google map and a slider made with JavaScript on the homepage of my rails app.

They work fine when the page gets loaded; however they do not work (carousel, map and slider are frozen) anymore if I go to any other page and then get back to the homepage.

the homepage (restaurant#index)

```
<div class="wrapper-meals">
  <div class="container text-center">
    <div class="col-sm-10 col-sm-offset-1">
      <div class="carousel">
        <% @restaurants.each do |r| %>
        <div class="carousel-item">
          <%= cl_image_tag(r.photo, secure: true, height: 200, width: 200, crop: :fill, quality: 100, alt: "plat du jour de #{r.name} chez Take a Meal") %>
          <h4 class="carousel-item--title"><%= r.name%></h4>
          <p class="carousel-item--description"><%= r.address %></p>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="wrapper-map">
  <div class="container text-center">
    <div>
      <div id="multi_markers" style='height: 500px;'></div>
    </div>
  </div>
</div>

<div class="pricing-wrapper">
  <div class="container text-center">
    <h3 class="pricing-title">SELECTIONNEZ VOTRE FORMULE</h3>
    <h5 class="pricing-subtitle">Le midi, du lundi au vendredi, pendant 30 jours. C'est <span class="pricing-subtitle--arg">sans engagement</span> et <span class="pricing-subtitle--arg">résiliable</span> à tout moment !</h5>
    <div class="row">
      <div class="col-sm-6 col-sm-offset-3">
        <div class="row">
          <div id="pricing-meal-numbers">
            <p class="pricing-meal--number">
              4
            </p>
            <p class="pricing-meal--number">
              8
            </p>
            <p class="pricing-meal--number">
              12
            </p>
            <p class="pricing-meal--number">
              16
            </p>
            <p class="pricing-meal--number">
              20
            </p>
          </div>
        </div>
        <div class="row">
          <input id="pricing-slider" type="range" min="4" max="20" value="12" step="4">
        </div>
      </div>
    </div>
    <div class="row">
      <h3><span id='unit-pricing'>XX</span>€/repas</h3>
    </div>
    <div class="row">
      <h5><span id='monthly-pricing'>ZZ</span>€/mois</h5>
    </div>
    <div class="row">
      <p class="pricing-arg">J'économise en moyenne <span id="pricing-arg--price">X</span>€ et <span id="pricing-arg--time">Yhyy</span> chaque mois !</p>
      <p class="pricing-arg--value">Profites-en plutôt pour <span id="pricing-arg--equiv">t'offrir des places de concert</span> ;)</p>
    </div>
    <div class="row">
      <% if current_user != nil %>
        <%= form_tag subscriptions_path, method: "get" do %>
        <%= hidden_field_tag 'chosen_subscription', '22'%>
        <%= submit_tag 'J\'EN PROFITE MAINTENANT !', class: 'btn pricing-cta' %>
        <% end %>
        <% else %>
          <%= form_tag new_user_registration_path, method: "get" do %>
          <%= hidden_field_tag 'chosen_subscription', '22'%>
          <%= submit_tag 'J\'EN PROFITE MAINTENANT !', class: 'btn pricing-cta' %>
        <% end %>
      <% end %>
    </div>
  </div>
</div>
<% content_for(:after_js) do %>
<%= javascript_tag do %>
var handler = Gmaps.build('Google');
handler.buildMap({ internal: { id: 'multi_markers' } }, function() {
markers = handler.addMarkers(<%= raw @hash.to_json %>);
handler.bounds.extendWith(markers);
handler.fitMapToBounds();
if (markers.length == 0) {
handler.getMap().setZoom(2);
} else {
handler.getMap().setZoom(14);
}
});
<% end %>
<%end %>
<% javascript_include_tag "carousel.js" %>
<% javascript_include_tag "pricing.js" %>
```

Here are my js files: carousel.js

```
$(document).ready(function(){
  $('.carousel').slick({
    SlidesToShow: 2,
    infinite: true,
    mobileFirst: true,
    variableWidth: true
  });
});
```
pricing.js

```
$(document).ready(function() {
  const pricingSlider = document.getElementById('pricing-slider');
  let unitPrice = document.getElementById('unit-pricing');
  let monthlyPrice = document.getElementById('monthly-pricing');
  let pricingArg = document.getElementById('pricing-arg--price');
  let timeArg = document.getElementById('pricing-arg--time');
  let pricingArgEquiv = document.getElementById('pricing-arg--equiv');
  let hiddenInput = document.getElementById('chosen_subscription');

    unitPrice.innerHTML = '6,49';
    monthlyPrice.innerHTML = '77,88';
    pricingArg.innerHTML = '48,12';
    timeArg.innerHTML = '3h20';
    pricingArgEquiv.innerHTML = 't\'offrir des places de concert';
    hiddenInput.value = '12'

    pricingSlider.addEventListener('change',() => {
      let subscription = event.target.value;
      if (subscription === '4') {
        unitPrice.innerHTML = '7,49';
        monthlyPrice.innerHTML = '29,96';
        pricingArg.innerHTML = '12,04';
        timeArg.innerHTML = '1h07';
        pricingArgEquiv.innerHTML = 'te faire un ciné';
        hiddenInput.value = '4'
      } else if (subscription === '8') {
        unitPrice.innerHTML = '6,99';
        monthlyPrice.innerHTML = '55,92';
        pricingArg.innerHTML = '28,08';
        timeArg.innerHTML = '2h13';
        pricingArgEquiv.innerHTML = 'faire un escape game';
        hiddenInput.value = '8'
      } else if (subscription === '12') {
        unitPrice.innerHTML = '6,49';
        monthlyPrice.innerHTML = '77,88';
        pricingArg.innerHTML = '48,12';
        timeArg.innerHTML = '3h20';
        pricingArgEquiv.innerHTML = 't\'offrir des places de concert';
        hiddenInput.value = '12'
      } else if (subscription === '16') {
        unitPrice.innerHTML = '6,24';
        monthlyPrice.innerHTML = '99,84';
        pricingArg.innerHTML = '68,16';
        timeArg.innerHTML = '4h27';
        pricingArgEquiv.innerHTML = 't\'offrir un massage';
        hiddenInput.value = '16'
      } else if (subscription === '20') {
        unitPrice.innerHTML = '5,99';
        monthlyPrice.innerHTML = '119,80';
        pricingArg.innerHTML = '90,20';
        timeArg.innerHTML = '5h33';
        pricingArgEquiv.innerHTML = 'partir en week-end';
        hiddenInput.value = '20'
      }

    });
  });
```
Any Idea on how I could get this work ?

**Comment by fordfischer** [comment]
I highly recommend reading the full readme even if it doesn't all make sense to you.

With turbolinks you should use

    document.addEventListener("turbolinks:load", function() {  YOUR_JAVASCRIPT })
instead of

    $(document).ready(function() { YOUR_JAVASCRIPT })

to initialize your javascript.

Now, making your javascript work on restoration visits (using the back button) can be a whole other matter, here is a stackoverflow question and answer I made a while ago when I ran into some problems. I specifically show how you can use the slick carousel.
https://stackoverflow.com/questions/39627881/jquery-plugin-initialization-on-browser-back-button-for-turbolinks-rails-5/39801052

**Comment by JulienCorb** [comment]
@fordfischer thank you for your help ! 

I acutally did that before, and here's what appened: 

I feel like when I get back to the page, the JS loads before the DOM: 

`let unitPrice = document.getElementById('unit-pricing');`should normally give something. 

But when i get back on the page: 

I get the following error `Uncaught TypeError: Cannot set property 'innerHTML' of null` which does not return null when the page is first loaded, but does when I get back to the page after a page change.

**Comment by JulienCorb** [comment]
Plus Your solution on [https://stackoverflow.com/questions/39627881/jquery-plugin-initialization-on-browser-back-button-for-turbolinks-rails-5/39801052](url) seems to work for going back to my homepage from any other page, so thanks a lot ! 

But it des not seem to do the trick when using the back button; still trying to find a way :)

**Comment by jbarnobal** [comment]
Got this problem too js break when changing pages
```
$(document).on('turbolinks:load', function(){
 $('.sidenav').sidenav(); 
})
```

**Comment by absolux** [comment]
@JulienCorb I "guess" the problem comes from how do you inject JavaScript into the controller's view.

I'm not pretty sure, but I think that `content_for(:after_js)`, `javascript_include_tag` will include `script` tags inside the `head` tag, and since turbolinks merges `head` tags, your scripts will only be evaluated once.

I suggest you to use simple `script` tags, or `javascript_tag`, directly within the view, to be re-evaluated each time the page is visited, since turbolinks will replace the `body` tag, even if the page is cached or not.

Hope it helps you.

PS: Remember to always `head` include your third party libraries (jquery, slider, google map...) to prevent a redownload or reeval for each page view.

**Comment by domchristie** [comment]
I think there are a few things going on here. First, when working with third-party scripts, it is usually worth considering manually setting them up and tearing them down. Good libraries should provide a way for both manual initialisation and teardown (e.g. `destroy()`) In Turbolinks apps, setting up is typically done on `turbolinks:load`, and teardown on `turbolinks:before-cache`. This is mentioned in [Preparing the Page to be Cached](https://github.com/turbolinks/turbolinks#preparing-the-page-to-be-cached).

Ideally your JavaScript should be contained within your main application bundle. Page-specific scripts can be confusing because they don't behave like they would in a traditional web app. In a traditional app, inline scripts become inactive once the page is navigated away from. In a Turbolinks app, the code is still "active" even after changing pages, so if you include a `turbolinks:load` event handler, it will not only run on that page, but also on every subsequent page. This is why you might have been seeing some errors like `Uncaught TypeError: Cannot set property 'innerHTML' of null`

To make your code Turbolinks-compatible, you might want to think about only running your functions when certain HTML is present on the page and making sure they are idempotent. This is explained in [Making Transformations Idempotent](https://github.com/turbolinks/turbolinks#making-transformations-idempotent).

You may also be facing a quirk with the way the Google Maps library works, so you may find the following helpful: https://github.com/turbolinks/turbolinks/issues/165#issuecomment-329890062

Hope that helps.

**Comment by stan74fr** [comment]
> Plus Your solution on [https://stackoverflow.com/questions/39627881/jquery-plugin-initialization-on-browser-back-button-for-turbolinks-rails-5/39801052](url) seems to work for going back to my homepage from any other page, so thanks a lot !
> 
> But it des not seem to do the trick when using the back button; still trying to find a way :)
> 
> If ever you have an idea for this...

the link URL seems to lead to an empty page. good if you could find the page again and link it back.

**Comment by nmoore2** [comment]
This helped me with the issue of an inline script duplicating on browser forward/back navigation

`document.currentScript.setAttribute("data-turbolinks-eval", "false");`
