### ISSUE TITLE
Function to update current page state in TuboLinks cache (5.2 version)

### ISSUE THREAD

**Issue by dummydummy775** [turbolinks/turbolinks#424]
Hi, 
   In my web application i do lot of caching on client side and update client side state of page using cached data. e.g: if use clicks a button ..instead of hitting server i load data from client side cache and update page state. 

Now i wish to save this changed page state in Turbo Links cache so that when i go to other page and come back to this same page i get to see the updated page state.  This does not happen as TurboLinks only tracks links click and ajax request changes.  

Is there a function in turbo link which i can call through my javascript to save latest page state .something like cacheCurrentPage() in turbolinks 3 version... Please advice how i can programmatically update cached page state using javascript.

**Comment by dummydummy775** [comment]
I wish to replace turbolinks cached state of page using a javascript function (e.g when user clicks a button and page state is updated from client side cached data) . Someone please reply with your thoughts on this.

Scenario is:

User comes to page2 from page1  by clicking some link on page1 . turbolinks caches page2 state (lets call it page2:state1) against link url

User clicks some **Button** (not link) on page2 and page state (lets call it page2:state2) is changed using client side cached data (**Note**: NO request is made to server side).

     Now i wish to register this changed state (page2:state2) in turbolinks cache by calling some function (which dies not make any server request) so that when i go  to some other page  and again come back to page2 i should see page2:state2...

Someone Please reply how i can achieve this .  

This can also be an enhancement feature so that users can rogramatically update page state in turbolinks cache for scenarios where page state is updated from client side cached data.

**Comment by domchristie** [comment]
Hi @dummydummy775 

Turbolinks caches a page just before it is navigated away from, so when someone returns to a cached page, it will be restored to how they left it. For example:

1. Visit page 1
2. Toggle some content to show it (without making a request)
3. Visit page 2
4. Tap "Back"
5. Page 1 will be rendered with the toggled content shown

This behaviour changes slightly if a link is clicked to revisit the page:

1. Visit page 1
2. Toggle some content to show it (without making a request)
3. Visit page 2
4. **Click link back to page 1**
5. Page 1 will be requested from the server
6. Page 1 **preview** will be rendered from the cache with the toggled content shown
7. Page 1 rendered with fresh content from the server

This is covered in more detail in [Navigating with Turbolinks](https://github.com/turbolinks/turbolinks#navigating-with-turbolinks).

---

Aside from clearing it completely, the Turbolinks cache has not been designed to be interacted with programmatically. You may find it useful to push to/replace the history as mentioned in this comment: https://github.com/turbolinks/turbolinks/issues/219#issuecomment-424817249 although note that this is not documented and so may change in future versions.

**Comment by domchristie** [comment]
@jduff yes, the preview may not be suitable in all cases but there are a couple of options:

1. Hook into the `before-cache` event and modify the DOM as needed. (Note that Turbolinks uses the cache for both previews and restoration visits (used after pressing Back/Forward), so it's not possible to customise a cached page for a preview or a restoration.)
2. Use the `no-preview` [`turbolinks-cache-control` directive](https://github.com/turbolinks/turbolinks#opting-out-of-caching). The downside being the loss of the perceived instantaneous performance.

> It seems like for the preview you would more likely want the initial dom contents, but for back button the final modified dom is more correct.

This is true is in your case, however the Turbolinks caching/preview behaviour is optimised for cases where the page is likely to reflect the state on the server. For example, consider a blog post with comments that are rendered dynamically via AJAX:

1. Visit blog post 1
2. Add a comment
3. Visit another post
4. Revisit post 1 (by clicking a link)
5. Preview is rendered which includes the comment as expected
6. Fresh copy is rendered, but because it's identical the you won't notice any difference 🎉 

Now of course this won't always be the case, and there may be a brief flash of old content before the fresh copy is rendered, but if the response is quick enough, the perceived effect will be snappy instantaneous page loads.

If it's likely that the preview will be very jarring, for example with significant page changes (or a customised form in your case), then it's probably best to follow the suggestions above.

Hope that helps

**Comment by jduff** [comment]
Thanks for clarifying all of this, really appreciate it!
