### ISSUE TITLE
turbolinks:before-visit not firing

### ISSUE THREAD

**Issue by dummydummy775** [turbolinks/turbolinks#429]
Hi,

    i wish to load cached version of page and not make any server call 
    (prevent server hit)  when links are clicked on navigation menu 
    in certain scenarios. 

    i.e  i wish to treat an Application Visits like a Restoration visit 
    in certain scenario on my web pages.
 
   As per documentaion on https://github.com/turbolinks/turbolinks#canceling-visits-before-they-start
   we can block Application visit.. 
   does this mean that clicked link will not open or it means that cached version of page will be
   loaded and no server request will be made to load new data..  
   
      I have this code on my jsp page

   document.addEventListener("turbolinks:load", function(event) {
	 alert('inside turbolinks:load ');
	});
	
document.addEventListener("turbolinks:before-visit", function(event) {
		   alert('inside turbolinks:before-visit 1');
	});
	
document.addEventListener("turbolinks:before-visit", function() {
		   alert('inside turbolinks:before-visit 2');
	});
	
when i come to this page from other pages the turbolinks:load fires and i see the alert...

but when i click certain navigation link on this page to go to some other page .. 
**turbolinks:before-visit**  **related function alerts are not seen**..

Kindly advice how to 
cause restoration visit like behaviour in certain scenarios when certain links are clicked.
 
**Note:** I wish to cause Application Visit in certain scenarios and Restoration visit like
         behaviour in other scenarios on the same link. How can i accomplish this.

**Comment by dummydummy775** [comment]
Any Suggestions friends, how this can be achieved.

Dear domchristie,

    kindly provide some suggestions.

    Thanks in advance

cheers,

**Comment by domchristie** [comment]
Hi @dummydummy775, sorry it has taken a while to get back to you on this.

> i wish to load cached version of page and not make any server call 
(prevent server hit)  when links are clicked on navigation menu 
in certain scenarios. 

Turbolinks has not been designed to work in this way. You may want to dig around in the source to figure out how the caching system works, and perhaps create a workaround for your case.

> we can block Application visit.. does this mean that clicked link will not open or it means that cached version of page will be
loaded and no server request will be made to load new data..

Cancelling a visit in a `before-visit` event means that the clicked link will not be loaded. It does not load from the cache.

I have not been able to reproduce your issue with `turbolinks:before-visit` not firing. If you can create a minimal demonstration, that might help to determine where the problem is.
