### ISSUE TITLE
Turbolinks, Stimulus, dynamic import(file.js) issue a blink, reloads div

### ISSUE THREAD

**Issue by frederikhors** [turbolinks/turbolinks#492]
### REPRODUCTION: https://glitch.com/edit/#!/salty-savory

I'm using Stimulus with Turbolinks and I need to dynamic import many js in controllers.

The code I'm using in `main.js` is:

```js
window.Turbolinks.start()

window.application = window.Stimulus.Application.start()

const IsPreviewPage = () => document.documentElement.hasAttribute('data-turbolinks-preview')

const divID = 'about_graphic'

window.application.register("about", class extends window.Stimulus.Controller {
  async initialize () {
    console.log("About, initialize()")
        
    if (IsPreviewPage()) {
      return
    }  

    const about = await import("./about.js")
    about.WriteInDiv()
  }
})

```

### THE PROBLEM

If I navigate to `/about` the first time the `Date.now()` appears.

Then I navigate to `/index`.

When I come back on the `/about` page the `Date.now()` reloads itself (you can see a blink after the preview page issued by Turbolinks).

**How can I avoid the div reload?**

In this one, I'm not using dynamic import and it doesn't reload: https://glitch.com/edit/#!/quintessential-reptile

# >>> **UPDATE**

It blinks (reloads div) just if I use:

```js
async initialize () {
  console.log("About, initialize()")
        
  if (IsPreviewPage()) {
    return
  }  

  await import("./about.js")
  WriteInDiv()
}

const WriteInDiv() = () => {...}
```

# Why?

**Comment by domchristie** [comment]
Hi @frederikhors,

I think you are seeing a blink because it takes a little while to import the `about.js` file. Here's what appears to be happening:

1. About preview renders and displays the old content ('Dynamic …')
2. About page loads from the server, and replaces the old content with 'Loading…'
3. `about` controller initialises and begins importing `about.js`
4. `WriteInDiv` executes and updates the content

Importing in step 3. can be relatively slow, and so the content will "blink" as it changes between 'Loading…' and the new dynamic content. A similar process happens with your non-blinking/no-import demo, but because there is no import, the content is updated immediately, so the change is imperceptible.

To avoid this, you might want to reorganise your code as follows. Use `about.js` to include all the `about` controller code (including the method to update the content). Then, load `about.js` as a script in the `<head>` of `about.html`. In this way, you have a nice separation of concerns: `about.js` contains with `about` controller codes and is automatically initialised when it loads. You also avoid the asynchronous complications of dynamically importing modules 🎉 

Here is a demo of that idea: https://glitch.com/edit/#!/thinkable-street

Does that solve your problem?

**Comment by frederikhors** [comment]
@domchristie First of all, thanks for the reply. Finding time to help others is a hallmark of greatness. Thanks again.

I fixed it like this:

```js
let aboutImportFile

window.application.register("about", class extends window.Stimulus.Controller {
  async initialize () {
    console.log("About, initialize()")
        
    if (IsPreviewPage()) {
      return
    }
    
    if (!aboutImportFile) {
      await import("./about.js").then(file => {
        aboutImportFile = file
      })
    }

    aboutImportFile.WriteInDiv()
  }
})
```

I think it may not be optimized for memory. What do you think about?

**Comment by frederikhors** [comment]
Update: added glitch reproduction (https://glitch.com/edit/#!/interesting-radish?path=main.js:1:0).

**Comment by domchristie** [comment]
Good to hear you've come up with a solution. 👍 

I think the solution proposed in https://github.com/turbolinks/turbolinks/issues/492#issuecomment-533898368 is preferable for a few reasons…

Firstly the about page code is self-contained within a single file, and is decoupled from `main.js`. There is no need to create export methods or call them from other files. This means you'll be able to make changes to `about.js` without worrying about breaking something somewhere else.

Secondly it reduces the number of conditional statements. Having lots of `if`s can be confusing as it increases the number of paths the code can take, and when debugging, every combination may need to be considered. Furthermore, removing the `IsPreviewPage` check eliminates the coupling to Turbolinks.

The solution is also easily adapted to comply with [Stimulus file naming conventions](https://stimulusjs.org/handbook/installing#controller-filenames-map-to-identifiers).

Finally, one of the main benefits of Turbolinks is that JavaScript files are only loaded and parsed once. By loading `about.js` via a script tag, you will speed up subsequent visits to the about page. If `about.js` is imported every time the `about` controller is initialised, you won't be getting this benefit.

If you're exploring code organisation with Stimulus, you may want to try discussing ideas on the [Stimulus Community Discourse](https://discourse.stimulusjs.org/).

**Comment by frederikhors** [comment]
Ok @domchristie thanks again. I understand your great explanation. It's so precious to me.

Just one doubt about:

> Furthermore, removing the IsPreviewPage check eliminates the coupling to Turbolinks.

What do you mean?

I'm using `IsPreviewPage` because I don't want anything to happen when I visit already visited page and I'm in preview waiting for news in background...

What I'm missing?

**Comment by domchristie** [comment]
> Furthermore, removing the IsPreviewPage check eliminates the coupling to Turbolinks.

With the `IsPreviewPage` check, your controllers include code that is tied to the way in which Turbolinks loads pages, and if this were to change, or if you were to remove Turbolinks, then you'd have to change all this.

This isn't a _huge_ deal, but most controllers should not be concerned with conditions in which they're loaded. It can become confusing if controllers are initialised in some cases but not others, and it is best to keep the code focussed on the behaviour and elements it controls.

There may be the odd case where you need to check for previews, but in cases such as the above, it isn't necessary.
