### ISSUE TITLE
checkmark not restored and js ignored

### ISSUE THREAD

**Issue by ArtemisGraphic** [turbolinks/turbolinks#508]
Hi,
I recently starded using turbolink with bootstrap but I'm facing a couple of issues, I followed the documentation and tried several solutions but i still have some issue, since the exclusive behavior of turbolinks on a webpage, I don't fully understand if the problem is unexpected or if I missed some configuration.

I have a page with checkbox and radio buttons. Normally, if I go back and forth from the page, the selections are "remembered" by the browser, but since I added turbolinks, each time I go back to that page I see the active checkmark for a second, and then they disappear. then, if I refresh the page, the checkmarks are restored.

Since I'm using bootstrap with a pure javascript library (bootstrap-native) I tried moving it into the head of the document with defer, but every animation or behavior are ignored (if you click on a checkbox, bootstrap add an '.active' class to the element, but if I put the .js in the head it does not work).

can you help me understandig and possibly fix this behavior?

thank you

**Comment by domchristie** [comment]
Hi @ArtemisGraphic

There are a couple of things going on here. Firstly, when you navigate to a previously visited page, and briefly see the previous state before it switches, you are seeing the Turbolinks preview feature ([Navigating with Turbolinks](https://github.com/turbolinks/turbolinks#navigating-with-turbolinks)and [Understanding Caching](https://github.com/turbolinks/turbolinks#understanding-caching) for more on this).

When using third-party libraries such as Bootstrap (or bootstrap-native) it is often best to manually call the JavaScript functions rather than relying on the library to do the work automatically (e.g. via `data-` attributes). Many libraries will listen out for the `DOMContentLoaded` event to initialise their components. For Turbolinks applications, this is only called on the first page load, so subsequent page loads won't behave in the same way. It's also good practice to tear down the effects of libraries on `turbolinks:before-cache`. This can often prevent components from being initialised more than once.

Finally, as https://github.com/turbolinks/turbolinks/issues/536 discusses, some browsers cache previously selected form field values and reinstate them on refresh. This can result in some odd behaviour as you've experienced.

I hope that clears things up.
