### ISSUE TITLE
External Javascript loads only after refresh

### ISSUE THREAD

**Issue by use0815** [turbolinks/turbolinks#538]
**Describe the bug**
I use turbolinks in Ruby on Rails applications. I have the following issue when using external Javascript on multiple sites and not found a solution yet: when I go to the site the Javascript doesn't get executed. After pressing refresh/F5 the code gets executed.

**To Reproduce**
A minimal demonstration of the issue can be *really* helpful, and will speed up our response time. Try remixing the Turbolinks demo on Glitch: https://turbolinks-demo.glitch.me/

1. Go to https://www.xn--bltenparadies-xob.de/de/map
2. The site contains Javascript from OpenStreatMap, but the map is not shown
3. Press refresh
4. The map is now visible

**Expected behavior**
The map should be displayed on the first load.

**Comment by kaspth** [comment]
This is not a bug in Rails, there’s the Turbolinks repo for that. Second, I don’t know if Turbolinks would consider this a bug either. This is expected behavior because of Turbolinks’ persistent process approach which some libraries can’t always handle. I think there’s an example on the Turbolinks issue tracker with OpenStreetMap, iirc, but could be wrong. Also check Turbolinks’ page events. Thanks, please do investigate! 🙏

**Comment by hortigado** [comment]
It is a turbolinks problem that I wish they would fix. you have to call them again when turbolinks load. When it would be better to cache the script as instantclick.io does than to back button the javascript is still alive so it helps me to have a carousel of images on the same site.
 $(document).on('turbolinks:load',function() {
 //call fuction again
 }

**Comment by domchristie** [comment]
The map seems to load when visiting from Firefox and Chrome (macOS).

If you are experiencing issues with third-party libraries, you may need reconsider how you integrate them. For example, if a third-party library initialises itelf on `DOMContentLoaded` you may need to find another way to manually initialise it.
