### ISSUE TITLE
Is there a version number provided in the source?

### ISSUE THREAD

**Issue by justin808** [turbolinks/turbolinks#6]
I'd like to have https://www.npmjs.com/package/react-on-rails, https://rubygems.org/gems/react_on_rails/versions/3.0.0.rc.1 support both Turbolinks Classic and Turbolinks 5.

What's the best way to determine which is which?

See: https://github.com/shakacode/react_on_rails/pull/264

CC: @aaronvb

**Comment by justin808** [comment]
I see https://github.com/turbolinks/turbolinks/blob/master/src%2Fturbolinks%2FVERSION

Maybe we can put that in a constant on the object Turbolinks?

**Comment by packagethief** [comment]
Hi Justin --

While I don't object to exposing the Turbolinks version to JavaScript, I think you're probably better off using feature detection for your case. Since Turbolinks Classic doesn't expose a version, you can't do a direct comparison -- you'll be doing a form of feature detection in any case.

Here's what I suggest. Test for `Turbolinks.EVENTS` to detect Turbolinks Classic. If you need to distinguish between Classic versions 2 and 3, test for `Turbolinks.EVENTS.PARTIAL_LOAD` which is only present in the latter.

If `Turbolinks.EVENTS` is undefined you can be sure you're using Turbolinks 5. Alternatively you can test for `Turbolinks.controller` which is only defined in version 5.

```coffee
Turbolinks.EVENTS # => Turbolinks Classic
Turbolinks.EVENTS.PARTIAL_LOAD # => Turbolinks Classic >= 3, < 5
Turbolinks.controller # => Turbolinks 5
```

**Comment by aaronvb** [comment]
@packagethief Thanks for your suggestion. :+1:

**Comment by justin808** [comment]
I think a version number would great regardless, and thanks @packagethief for the tips. Please close unless you want to leave open until you add a version number, if you wish to do that.
