### ISSUE TITLE
Can turbolinks-root be used to include subdomains?

### ISSUE THREAD

**Issue by apuntovanini** [turbolinks/turbolinks#63]
Hi, can we use turbolinks-root options to let Turbolinks intercept links with specific url pattern (might be a Regex - or "All domain and subdomain related to x".
I tried "*" with no success so far
Thanks in advance
Andrea

**Comment by packagethief** [comment]
Hi Andrea,

Sorry, `turbolinks-root` can't be used to include subdomains. It's only useful for constraining same-origin requests to a particular path prefix.

Alas, Turbolinking to a different subdomain won't work in any case, because `XMLHttpRequest` is subject to the [same-origin policy](https://developer.mozilla.org/en-US/docs/Web/Security/Same-origin_policy). Different subdomains on the same domain are considered cross-origin.

**Comment by apuntovanini** [comment]
Thanks a lot for the quick reply and for the explanation.
I understand the same-origin policy issue, maybe CORS can be used to work it around (http://www.html5rocks.com/en/tutorials/cors/)
If I'm not the alone with this issue I might work on a pull request around the createXHR method (https://github.com/turbolinks/turbolinks/blob/master/src/turbolinks/http_request.coffee#L62)
What do you think @packagethief?
Thanks a lot

**Comment by sstephenson** [comment]
Unfortunately the HTML History API doesn’t support `pushState` or `replaceState` on a different domain, so I’m afraid cross-domain navigation is a non-starter.

**Comment by apuntovanini** [comment]
Yea, you're right @sstephenson, then there are no workarounds on this? Thanks
