### ISSUE TITLE
is it possible to pause render before everything is loaded?

### ISSUE THREAD

**Issue by sandrodz** [turbolinks/turbolinks#68]
I'm animating page loads using turbolinks and animate.css.

I've got it setup pretty nicely:
```javascript
$(document).on('turbolinks:before-render', function(e) {
  var aIn = $('body').data('animation-in');
  $(e.originalEvent.data.newBody).addClass('animated u-noneInteractive ' + aIn)
    .one('webkitAnimationEnd mozAnimationEnd MSAnimationEnd oanimationend animationend', function(){ $('body').removeAttr('class'); });
});
```

I want to move this 1 step ahead and add loading animation.

So in theory I'd wait for

```javascript
$(window).load(function(){
  //your code here
});
```

Is this possible with turbolinks available events?

**Comment by nateberkopec** [comment]
Most of the time, when people want to wait for `window.load`, they can replace it with `turbolinks:render`. Does that not work for you?

TBH I don't know what you mean by "move 1 step ahead and add loading animation".

**Comment by sandrodz** [comment]
so `window.load` in terms of turbo links becomes `turbo links:render` all images are downloaded at that point?

in other words, I would use before-render to hide content and render to animate?

**Comment by nateberkopec** [comment]
Aha! Now I see what you mean. No, it isn't an exact equivalent. `window.load` fires after all sub-resources, such as images have been downloaded. `turbolinks:render` fires right after the `body` is replaced, and images may not have finished downloading yet.

Rather than waiting for `window.load` (which may be slowed down by unrelated downloads, like a script), I think you should be trying event delegation:

```javascript
$(document).on("load", "img", function () { 
  // animation stuff
});
```

**Comment by sstephenson** [comment]
No, sorry, it’s not currently possible to defer rendering. That’s an interesting idea, though.
