### ISSUE TITLE
Question: Should we add ids to dom elements?

### ISSUE THREAD

**Issue by TangRufus** [turbolinks/turbolinks#69]
Is adding ids to dom elements makes turbolinks faster?
Or, it doesn't matter?

Thanks!

**Comment by nateberkopec** [comment]
Your question is pretty broad (faster under what circumstances?), but, in general, Turbolinks will greatly benefit from CSS that is written with performance in mind.

Because Turbolinks replaces the *entire* body element on every navigation, the entire `body` has its styles recalculated, layout re-done, and finally must be re-painted to the screen. Unlike frontend solutions that use a virtual DOM, like React, the *entire* DOM must be replaced and restyled. This happens even if only 1 DOM element out of 4,000 is different. On large, 2,000+ DOM element pages, this can become a minor bottleneck. On my 4,000-element test page, style recalculation/layout/paint takes about 100 milliseconds. That's not the end of the world, but 100 milliseconds can be the difference in making Turbolinks navigation feel "native-like" or "instantaneous".

So, how can a Turbolinks application use CSS to make the style recalculation/layout/paint process faster?

* **Use smarter CSS selectors**. As you mentioned, certain selectors are faster than others. The fastest CSS selectors tend to be just a single class or ID. Avoid child or descendant selectors. [MDN has a complete article on the topic.](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Writing_efficient_CSS) Simply adding IDs to elements won't make Turbolinks any faster, though rewriting your site's CSS to use simple class and ID selectors will.
* **Use flexbox** According to Google, flexbox is now a faster layout model for most websites than traditional, float-based layouts. Your mileage may vary, profile and benchmark to make sure.
* **Write less CSS** Style and layout will be faster if there's simply less CSS to apply. Try and keep it under about ~100KB.
* **Keep DOM sizes under 1,000 elements** Less complex DOMs are faster to style and paint. You can check the size of any webpage's DOM by putting `document.getElementsByTagName('*').length` into the console.

[Google Web Fundamentals](https://developers.google.com/web/fundamentals/performance/rendering/?hl=en) provides an in-depth introduction to rendering performance.

For small, simple webpages (~250 DOM elements or less), none of this is really an issue.
