### ISSUE TITLE
problem using relative image urls

### ISSUE THREAD

**Issue by bmesuere** [turbolinks/turbolinks#82]
I'm using relative paths for images on my page. When I navigate away from a page containing such images, it tries to reload the images of the previous page using the base url of the next page resulting in a bunch of 404's.

The top few lines of the stack trace in chrome:
```
Image (async)		
Turbolinks.View.e.getSnapshot
Turbolinks.Controller.t.cacheSnapshot
Turbolinks.Visit.t.cacheSnapshot
requestAnimationFrame (async)		
Turbolinks.Visit.t.render
Turbolinks.Visit.t.loadResponse
Turbolinks.BrowserAdapter.t.visitRequestCompleted
Turbolinks.Visit.t.requestCompletedWithResponse
```

To reproduce, visit http://dodona.ugent.be/exercises/akkoorden/ and click "Oefeningen" in the top header. I'm using Turbolinks 5.0.0beta2.

**Comment by packagethief** [comment]
Thanks @bmesuere. I confirmed this is a side-effect of using [`Element.cloneNode`](https://developer.mozilla.org/en-US/docs/Web/API/Node/cloneNode). When cloning an `<img>` element the browser will request its URL, even if the element isn't attached to the DOM (the same is true for other media elements). When the URL is relative, it's resolved from `window.location`. Since Turbolinks caches the current page after history has been changed to the next page, the base might be incorrect.

The simplest thing to do is to avoid using relative image URLs, at least for now :grin:
