### ISSUE TITLE
Turbolinks ProgressBar API

### ISSUE THREAD

**Issue by kevinhughes27** [turbolinks/turbolinks#93]
Turbolinks-classic and Turbolinks 3 had an API to interact with the ProgressBar but Turbolinks 5 seems to have removed this functionality. I didn't see any mention of why in the documentation so I am opening this issue to discuss. The ProgressBar API was useful for having a consistent feel if your app made other ajax requests not through Turbolinks, for example something like this:

```javascript
Turbolinks.ProgressBar.start();

$.ajax({
  ...
}).done(function() {
  Turbolinks.ProgressBar.done()
});
```

I'd be happy to work on exposing this if its something that would be accepted.

@sstephenson

**Comment by GLiberman** [comment]
In case if you didn't find it yet

start -> 
Turbolinks.controller.adapter.progressBar.setValue(0)
Turbolinks.controller.adapter.progressBar.show()

done -> 
Turbolinks.controller.adapter.progressBar.setValue(100)
Turbolinks.controller.adapter.progressBar.hide()

**Comment by kevinhughes27** [comment]
I did see that you can do that. I am proposing that we expose this as a top level function to avoid reaching through 3 layers to start the progress bar.

**Comment by nateberkopec** [comment]
Although @GLiberman's solution does work, worth nothing that @sstephenson only considers the functions in [index.coffee](https://github.com/turbolinks/turbolinks/blob/master/src/turbolinks/index.coffee) to be Turbolinks' "public API" - everything else is private.

**Comment by sstephenson** [comment]
@nateberkopec’s correct—you can reach into the Turbolinks internals and control the progress bar yourself, but be warned that the API may change at any time in the future.

Exposing a public progress bar API might seem easy enough, but there are some important considerations to keep in mind:

1. **The progress bar is not reentrant.** It expects to be controlled by one request at a time. What should happen if Turbolinks is loading a page and your app is loading a resource, too? What if your app is loading more than one resource simultaneously?
2. **The [native](https://github.com/turbolinks/turbolinks-ios/blob/master/Turbolinks/WebView.js) [adapters](https://github.com/turbolinks/turbolinks-android/blob/master/turbolinks/src/main/assets/js/turbolinks_bridge.js) don’t have a progress bar.** It’s installed on the [browser adapter](https://github.com/turbolinks/turbolinks/blob/09cb42f2c876b5d816ea1ee1e900cd86f798b5e1/src/turbolinks/browser_adapter.coffee#L9) only. This makes sense if the progress bar is only for navigation, because the native adapters show their own progress indicators—but you probably want to see progress for e.g. Ajax actions on your pages, too.
3. **Local activity indicators usually provide a better experience.** People are generally accustomed to seeing navigation progress indicators at the top of the screen when moving from page to page. But in my experience, for things like form submission and lazily loaded content, app-specific progress indicators localized to the site of action work best.

For these reasons I don’t think we’ll be opening up the Turbolinks progress bar.

**Comment by kevinhughes27** [comment]
Okay thanks for your response. I will implement something separate for my needs.
