### ISSUE TITLE
Documentation for Blade

### ISSUE THREAD

**Issue by ajb** [turbolinks/turbolinks#98]
Turbolinks is built / tested with Blade, but Blade lacks any kind of documentation.

**Comment by javan** [comment]
[Blade](https://github.com/javan/blade) provides a convenient [Sprockets](https://github.com/rails/sprockets) API, much like [sprockets-rails](https://github.com/rails/sprockets-rails) does. It also sets up a [QUnit](http://qunitjs.com/) test runner.

Apologies for the lack of documentation. I plan to write some and welcome help. Closing because this isn't really a Turbolinks issue. Feel free to open one with Blade.

**Comment by ajb** [comment]
Thanks @javan. Was reluctant to open over there since it's a personal repo, and there's not much activity from anyone besides yourself :). I figured that now was a decent time to ask, though, since it's a dependency of Turbolinks, which is (I think?) included in Rails by default.
